version: "2"
services: 
  stable-diffusion-webui-rocm:
    cap_add:
      - SYS_PTRACE
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      # VERY COMMON NEED ENVIRONMENT VARIABLE
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      # Following line is needed to RX 5700
      # - COMMANDLINE_ARGS='--precision full --no-half'
    image: stable-diffusion-webui-rocm:latest
    ipc: host
    network_mode: "host"
    shm_size: "8G"
    security_opt:
      - seccomp:unconfined
    volumes:
      - configs:/sd/configs
      - models:/sd/models
      - plugins:/sd/plugins
      - outputs:/sd/outputs
      - extensions:/sd/extensions
volumes:
  configs:
  models:
  plugins:
  outputs: 
  extensions:
